# Select base image
FROM nvcr.io/nvidia/deepstream:6.1.1-devel

# Install additional packages
WORKDIR /opt/nvidia/deepstream/deepstream
RUN ./user_additional_install.sh

# Install required dependencies
RUN apt install ffmpeg python3-gi python3-dev python3-gst-1.0 python-gi-dev git python-dev \
    python3 python3-pip python3.8-dev cmake g++ build-essential libglib2.0-dev \
    libglib2.0-dev-bin libgstreamer1.0-dev libtool m4 autoconf automake libgirepository1.0-dev libcairo2-dev -y
    
# Initialization of submodules
WORKDIR /opt/nvidia/deepstream/deepstream/sources 
RUN git clone https://github.com/NVIDIA-AI-IOT/deepstream_python_apps.git
WORKDIR /opt/nvidia/deepstream/deepstream/sources/deepstream_python_apps
RUN git submodule update --init

# Installing Gst-python
RUN apt-get install -y apt-transport-https ca-certificates -y
RUN update-ca-certificates
WORKDIR /opt/nvidia/deepstream/deepstream/sources/deepstream_python_apps/3rdparty/gst-python
RUN ./autogen.sh
RUN make
RUN make install

# Compiling python bindings
WORKDIR /opt/nvidia/deepstream/deepstream/sources/deepstream_python_apps/bindings
RUN mkdir build
WORKDIR /opt/nvidia/deepstream/deepstream/sources/deepstream_python_apps/bindings/build
RUN cmake .. -DPYTHON_MAJOR_VERSION=3 -DPYTHON_MINOR_VERSION=8
RUN make

# Installing python bindings
RUN pip3 install ./pyds-1.1.4-py3-none*.whl

# Install jupyterlab and packages
WORKDIR /opt/nvidia/deepstream/deepstream-6.1
RUN pip3 install jupyterlab \
    ipywidgets \
    matplotlib \
    scipy \
    imutils \
    opencv-python

